server:
  port: 8080
spring:
  application:
    name: user-service
azure:
  cosmos:
    uri: https://ticketing-db.documents.azure.com:443/
    key: x
    database: ticketing-management-db

logging:
  level:
    com.example.userservice: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

