replicaCount: 2
image:
  repository: user-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
env:
  - name: AZURE_COSMOS_URI
    value: "<replace-with-uri>"
  - name: AZURE_COSMOS_KEY
    value: "<replace-with-key>"
resources: {}