name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Build Docker image
        run: docker build -t user-service:latest .
      - name: Push to registry (placeholder)
        run: echo "Push to Docker registry"
      - name: Deploy to AKS with Helm
        run: |
          helm upgrade --install user-service ./helm/user-service \
            --set image.repository=user-service \
            --set image.tag=latest