name: Build and Deploy to AKS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  ACR_NAME: acr4anil
  IMAGE_NAME: user-service
  CLUSTER_NAME: aks4ticketing
  RESOURCE_GROUP: ticketing
  NAMESPACE: ticketing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Images (SHA + latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64

      - name: Set AKS Context
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Create namespace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Deploy to AKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml -n $NAMESPACE
          kubectl apply -f kubernetes/service.yaml -n $NAMESPACE
